disp('Problem 1')
disp(['Bank TYU promises a monthly return of 0.80% if you deposit ' ...
    '$145 each month for 10 years, similar to a Certificate of Deposit (CD). ' ...
    'How much will you have at the end of those 10 years?']);
A = (((1 + 0.008)^120 - 1) / 0.008) * 145;
sprintf("%.2f",A)

disp('Problem 2')
disp(['Kenneth is contributing to his 401(k) retirement plan. ' ...
    'He contributes $3,500 per year. His employer matches 50% of his contribution. ' ...
    'If Kenneth can earn a 9.0% rate of return, ' ...
    'how much will he have in his account after 15 years?']);
A = (((1 + 0.09)^15 - 1) / 0.09) * 5250;
sprintf("%.2f", A)

disp('Problem 3')
disp(['Maria needs to save $47,000 over the next 4 years. ' ...
    'If she can save $6,000 per year and earn an 12.0% rate of ' ...
    'return on an annualized basis, by how much will she exceed or ' ...
    'fall short of her goal?'])
A = (((1 + 0.12)^4 - 1) / 0.12) * 6000;
A = 47000 - A;
sprintf("%.2f", A)

disp('Problem 4')
disp(['Amy has $5,000 saved to buy a new car. ' ...
    'If she can earn a 9.5% rate of return, ' ...
    'how much will she have at the end of 3 years?'])
A = (5000)*((1 + 0.095)^3);
sprintf("%.2f", A)

disp('Problem 5')
disp(['A car will cost $27,000 in 5 years. ' ...
    'If you can earn 10.0% on an investment, ' ...
    'how much would you need to invest today ' ...
    'to make sure that you can afford the car at the end of 5 years?'])
A = 27000/((1.1)^5);
sprintf("%.2f", A)

disp('Problem 6')
disp(['As part of your estate planning, ' ...
    'Andrew needs to know the future value of his assets. ' ...
    'He is currently 37 years old, with a life expectancy of 75 years. ' ...
    'His most valuable asset is his house, which is currently worth $289,000. ' ...
    'The house is expected to appreciate at a rate of 10.5% per year. ' ...
    'How much should he project for the house value in his estate plan?'])
A = (289000)*((1 + 0.105)^38);
sprintf("%.2f", A)

disp('Problem 7')
disp(['Ana has $100,000 to invest. ' ...
    'Her financial planner recommended investing 50% in bonds and 50% in equities. ' ...
    'Since equity investments are riskier than bonds, the expected return' ...
    ' on equities is 16.5%, while the expected return on bonds is 5.5%. ' ...
    'How much does Ana expect to have at the end of 6 years if she follows ' ...
    'this investment strategy?'])
A = (50000)*((1 + 0.165)^6);
B = (50000)*((1 + 0.055)^6);
C = A + B
sprintf("%.2f", C)

disp('Problem 8')
disp(['An acquaintance has been persistently trying to convince you to invest' ...
    ' in a scheme that promises to double your investment every 4 months. ' ...
    'What is the APY of that dubious scheme?'])
A = ((1 + (1.00/3))^3) - 1
A = A*100
sprintf("%.2f", A)

disp('Problem 10')
disp(['Larry hopes to buy a house in 9 years. ' ...
    'He currently has $77,700 saved. ' ...
    'How much must he earn in interest on an annualized basis ' ...
    'to purchase a house valued at $184,300?'])
A = ((184300/77700)^(1/9)) - 1
A = A * 100
sprintf("%.2f", A)

disp('Problem 11')
disp(['Oliver has a public student loan of $53,600 with a 12-year ' ...
    'fixed repayment plan and an interest rate of 6.0%. ' ...
    'If the government forgives 24% of his debt, by ' ...
    'how much would his monthly payments be reduced?'])
A = 53600/((((1 + 0.06)^144) - 1)/0.06);
sprintf("%.2f", A)
B = 40736/((((1 + 0.06)^144) - 1)/0.06);
sprintf("%.2f", B)
C = A - B;
sprintf("%.2f", C)
disp("Probably not correct")

disp('Problem 12')
disp(["You want to buy a house worth $200,000, " + ...
    "and the bank offers you a 25-year " + ...
    "mortgage with an interest rate of " + ...
    "7.5%. If you plan to pay 35% of the house " + ...
    "in cash and cover the remaining amount with the mortgage, " + ...
    "how much will your monthly mortgage payment be?"])
A = 130000*((0.00625*(1.00625^300))/((1.00625^300) - 1));
sprintf("%.2f", A)

disp('Problem 13')
disp("John is considering his employer's offer of early retirement. " + ...
    "The company will pay a pension benefit of $3,700 a month until he " + ...
    "turns 95, which means a 30-year plan starting now. " + ...
    "If he can earn 6.5% APR on his money, what is the approximate present" + ...
    " value of the pension payments?")
A = 3700 * ((1 - (1 + (0.065/12))^(-360)) / (0.065/12));
sprintf("%.2f", A)

